upgrade to python3.9, still raises AttributeError: module 'serial' has no attribute 'SerialException' but could be because of no arduino connected. To be checked -fh'